In [1]:
#Importando as bibliotecas
from sklearn import cluster, neighbors,metrics
import numpy as np

In [2]:
#importando a base
dacc=np.load("/Users/LENOVO/Documents/Análise de dados com Python/KNN/daccpca.npy")

In [3]:
#Número de linhas das dados. Ou seja numero de amostras:
len(dacc)

522

In [4]:
#Rótulos das amostras
dacc[:,-1]

array([4., 2., 2., 1., 1., 1., 1., 1., 4., 2., 3., 1., 2., 2., 1., 2., 1.,
       2., 2., 2., 3., 1., 2., 1., 1., 3., 5., 3., 2., 1., 1., 2., 2., 2.,
       1., 0., 2., 0., 2., 2., 2., 1., 5., 2., 2., 2., 1., 0., 1., 2., 1.,
       2., 3., 0., 2., 0., 0., 2., 0., 2., 2., 2., 6., 2., 2., 2., 1., 0.,
       1., 2., 1., 3., 2., 1., 2., 2., 2., 2., 6., 2., 2., 0., 2., 6., 2.,
       2., 2., 2., 0., 3., 2., 2., 2., 6., 2., 2., 2., 0., 2., 0., 4., 2.,
       2., 1., 0., 1., 2., 4., 2., 1., 2., 2., 2., 1., 1., 3., 2., 4., 4.,
       1., 2., 2., 3., 2., 2., 2., 1., 1., 2., 2., 1., 0., 5., 6., 2., 3.,
       2., 2., 2., 2., 3., 2., 0., 6., 6., 2., 3., 0., 3., 3., 1., 2., 0.,
       0., 2., 0., 2., 2., 2., 0., 0., 2., 2., 5., 3., 3., 0., 2., 2., 3.,
       5., 2., 2., 4., 2., 2., 2., 1., 3., 1., 1., 1., 1., 1., 2., 1., 2.,
       2., 4., 1., 1., 2., 2., 2., 1., 1., 2., 4., 1., 6., 1., 2., 2., 2.,
       1., 1., 1., 3., 1., 2., 1., 2., 2., 3., 2., 1., 5., 4., 2., 3., 3.,
       2., 3., 2., 3., 2.

# Usando classificação supervisinado com o método k-nn (k vizinhos mais próximos)

In [5]:
clf = neighbors.KNeighborsClassifier(5, metric='euclidean',weights='distance')

In [6]:
#Treinamento do modelo KNN

In [7]:
clf.fit(dacc[:,0:-2], dacc[:,-1])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='distance')

In [8]:
#Fazendo a predição dos dados
z=clf.predict(dacc[:,0:-2])

In [9]:
z

array([4., 2., 2., 1., 1., 1., 1., 1., 4., 2., 3., 1., 2., 2., 1., 2., 1.,
       2., 2., 2., 3., 1., 2., 1., 1., 3., 5., 3., 2., 1., 1., 2., 2., 2.,
       1., 0., 2., 0., 2., 2., 2., 1., 5., 2., 2., 2., 1., 0., 1., 2., 1.,
       2., 3., 0., 2., 0., 0., 2., 0., 2., 2., 2., 6., 2., 2., 2., 1., 0.,
       2., 2., 1., 3., 2., 1., 2., 2., 2., 2., 6., 2., 2., 0., 2., 6., 2.,
       2., 2., 2., 0., 3., 2., 2., 2., 6., 2., 2., 2., 0., 2., 0., 4., 2.,
       2., 1., 0., 1., 2., 4., 2., 1., 2., 2., 2., 1., 1., 3., 2., 4., 4.,
       1., 2., 2., 3., 2., 2., 2., 1., 1., 2., 2., 1., 0., 5., 6., 2., 3.,
       2., 2., 2., 2., 3., 2., 0., 6., 6., 2., 3., 0., 3., 3., 1., 2., 0.,
       0., 2., 0., 2., 2., 2., 0., 0., 2., 2., 5., 3., 3., 0., 2., 2., 3.,
       5., 2., 2., 4., 2., 2., 2., 1., 3., 1., 1., 1., 1., 1., 2., 1., 2.,
       2., 4., 1., 1., 2., 2., 2., 1., 1., 2., 4., 2., 6., 1., 2., 2., 2.,
       1., 1., 1., 3., 1., 2., 1., 2., 2., 3., 2., 1., 5., 4., 2., 3., 3.,
       2., 3., 2., 3., 2.

# Vamos calcular a acurácia da classificação:

In [11]:
#Resultado excepcionalmente bom com 98,65% de acuracia
metrics.accuracy_score(dacc[:,-1],z)

0.9865900383141762

In [12]:
#Matriz de confusão mostrando que a classificação é muito boa.
metrics.confusion_matrix(dacc[:,-1],z)


array([[ 44,   0,   0,   0,   0,   0,   0],
       [  0, 151,   6,   0,   0,   0,   0],
       [  0,   0, 229,   0,   0,   0,   0],
       [  0,   0,   1,  44,   0,   0,   0],
       [  0,   0,   0,   0,  22,   0,   0],
       [  0,   0,   0,   0,   0,  10,   0],
       [  0,   0,   0,   0,   0,   0,  15]], dtype=int64)